### ISSUE TITLE
diff output  by diff run with same file with same para 

### ISSUE THREAD

**Issue by hewm2008** [wahlflo/eml_analyzer#14]
the same input  the same para
but random out  with xxx  by diff run 
the input file is here :     [aaa_123.zip](https://github.com/wahlflo/eml_analyzer/files/11145813/aaa_123.zip)
![image](https://user-images.githubusercontent.com/10345833/229719442-8451ea5f-a1a7-456a-ad68-78c3c09d1b80.png)

**Comment by wahlflo** [comment]
I can reproduce the issue and will have a look into it

**Comment by wahlflo** [comment]
okay silly bug... The list of possible encodings was a set rather a list. First the encoding from the given in the email and if they not work  then common encodings should be tried out. Using the set just shuffled the encodings...  
I pushed the fix to the branch linked to this issue.

**Comment by wahlflo** [comment]
@hewm2008 Thank you for your hint!
