### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by HFANFA** [wahlflo/eml_analyzer#19]
This is a very convenient and powerful tool library; but when I use it to parse emails(Chinese email or English email) in batches, the following errors occasionally occur:
File "D:\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\Scripts\emlAnalyzer.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\lib\site-packages\eml_analyzer\cli_script.py", line 66, in main
    output_format.process_option_show_html(parsed_email=parsed_email)
  File "D:\anaconda3\lib\site-packages\eml_analyzer\library\outputs\standard_output.py", line 62, in process_option_show_html
    print(html)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 45613: illegal multibyte sequence

For coding problems, I don't have a solution，My execution environment is Windows.
Due to the confidentiality of the email content, I am sorry that I cannot provide.

**Comment by wahlflo** [comment]
Hi @HFANFA,
I'm glad you like it 😄 

> Due to the confidentiality of the email content

I can unterstand that but without at least fragments of the emails I will not be able to fix the issue. 

Can you maybe create a minimalistic email based on the original ones which would  generate this error? 

Try to use the same headers related to enconding and the same character where the library has issues to decode them.

**Comment by HFANFA** [comment]
Thank you very much for your quick response. After further testing, I found that the issue only occurs with emails that use base64 encoding for the body. When I use Python or PowerShell to invoke eml_analyzer and capture the terminal output, I encounter the problem mentioned earlier. However, when I directly use the terminal command to process these emails, it works correctly. I believe this may be an issue with my terminal setup rather than eml_analyzer itself. I apologize for taking up your time and attention. Lastly, I want to say that eml_analyzer is a fantastic tool!
Your can close this issue.😄
